"""Change code column type to BLOB

Revision ID: 0517a0b716ee
Revises: 46777e0526aa
Create Date: 2022-10-29 18:53:49.860008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0517a0b716ee'
down_revision = '46777e0526aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
