"""Add cascade delete

Revision ID: 1c26c3d8045b
Revises: 9dc731723d72
Create Date: 2022-10-31 09:09:38.046104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c26c3d8045b'
down_revision = '9dc731723d72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calculators_author_id_fkey', 'calculators', type_='foreignkey')
    op.create_foreign_key(None, 'calculators', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calculators', type_='foreignkey')
    op.create_foreign_key('calculators_author_id_fkey', 'calculators', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
