"""Set code column to be not unique

Revision ID: 453bb71c68cf
Revises: 46777e0526aa
Create Date: 2022-10-29 20:16:38.936331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453bb71c68cf'
down_revision = '46777e0526aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('calculators_code_key', 'calculators', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('calculators_code_key', 'calculators', ['code'])
    # ### end Alembic commands ###
