"""Change owner_id column name to author_id

Revision ID: 46777e0526aa
Revises: ec7b1fb5974f
Create Date: 2022-10-29 15:50:45.915048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46777e0526aa'
down_revision = 'ec7b1fb5974f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculators', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint('calculators_owner_id_fkey', 'calculators', type_='foreignkey')
    op.create_foreign_key(None, 'calculators', 'users', ['author_id'], ['id'])
    op.drop_column('calculators', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculators', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calculators', type_='foreignkey')
    op.create_foreign_key('calculators_owner_id_fkey', 'calculators', 'users', ['owner_id'], ['id'])
    op.drop_column('calculators', 'author_id')
    # ### end Alembic commands ###
