"""Fixes for lab7

Revision ID: 9dc731723d72
Revises: 18acc04e566b
Create Date: 2022-10-30 14:27:09.707974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc731723d72'
down_revision = '18acc04e566b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculators', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.add_column('calculators', sa.Column('author_id', sa.Integer(), nullable=False))
    op.drop_constraint('calculators_code_key', 'calculators', type_='unique')
    op.drop_constraint('calculators_owner_id_fkey', 'calculators', type_='foreignkey')
    op.create_foreign_key(None, 'calculators', 'users', ['author_id'], ['id'])
    op.drop_column('calculators', 'owner_id')
    op.drop_column('calculators', 'codePrivacy')
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('calculators', sa.Column('codePrivacy', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('calculators', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'calculators', type_='foreignkey')
    op.create_foreign_key('calculators_owner_id_fkey', 'calculators', 'users', ['owner_id'], ['id'])
    op.create_unique_constraint('calculators_code_key', 'calculators', ['code'])
    op.drop_column('calculators', 'author_id')
    op.drop_column('calculators', 'is_public')
    # ### end Alembic commands ###
