"""Add password column

Revision ID: ec12b2ba3282
Revises: 18acc04e566b
Create Date: 2022-10-28 20:26:41.792479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec12b2ba3282'
down_revision = '18acc04e566b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculators', sa.Column('isPublic', sa.Boolean(), nullable=False))
    op.drop_column('calculators', 'codePrivacy')
    op.add_column('users', sa.Column('password', sa.String(length=100), server_default='Legacy', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('calculators', sa.Column('codePrivacy', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('calculators', 'isPublic')
    # ### end Alembic commands ###
